In [34]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
df = pd.read_csv("../data/oil_production.csv")
prices = pd.read_csv('../data/oil_prices.csv')

print('PetroView Environment is Ready')

PetroView Environment is Ready

In [ ]:
import plotly.express as px

fig = px.bar(
    df,
    x="country",
    y="production",
    title="Top Oil Producing Countries"
)
fig.show()

In [ ]:
df_sorted = df.sort_values(by='production',ascending=False)
df_sorted.head(3)
total_supply = df['production'].sum()
total_supply

np.int64(57700)

In [ ]:
df['share_percent'] = (df['production'] / total_supply) * 100
df

         country  production  share_percent
0  United States       12000      20.797227
1   Saudi Arabia       10500      18.197574
2         Russia       10000      17.331023
3         Canada        5000       8.665511
4          China        4000       6.932409
5           Iraq        4500       7.798960
6            UAE        3500       6.065858
7         Brazil        3000       5.199307
8           Iran        2500       4.332756
9         Kuwait        2700       4.679376

In [ ]:
df_sorted = df.sort_values(by='share_percent',ascending=False)
df_sorted 
fig = px.bar(
    df_sorted,
    x='country',
    y='share_percent',
    title='Share of Global Oil Production'
)
fig.show()

In [35]:
fig = px.line(
    prices,
    x="year",
    y="oil_price",
    title="Global Oil Prices Over Time"
)
fig.show()

In [39]:
data = {
    "year":[2018,2019,2020,2021,2022,2023],
    "global_supply":[95,97,90,96,99,101],
    "oil_price":[65,70,40,75,95,85]
}

oil_df = pd.DataFrame(data)

oil_df

   year  global_supply  oil_price
0  2018             95         65
1  2019             97         70
2  2020             90         40
3  2021             96         75
4  2022             99         95
5  2023            101         85

In [ ]:
fig = px.scatter(
    oil_df,
    x='global_supply',
    y='oil_price',
    title='Oil Supply vs Oil Price'
)
fig.show()

In [44]:
fig = px.scatter(
    oil_df, 
    x='global_supply',
    y='oil_price',
    trendline='ols',
    title='Oil Supply vs Price Relationship'
)
fig.show()